# Linear Algebra

# Fundamentos


## Escalares

In [1]:

x1 = 2
x2 = 0.4
x3 = -2

## Vetores

In [2]:
import numpy as np

In [3]:
# Criação de dois vetores (A [2, 2] e B[5, 3])
A = np.array([ 2, 2 ])
B = np.array([ 5, 3])

In [4]:
B

array([5, 3])

## Matrizes


In [5]:
# Matriz 3x2 com números de 1 a 6
A = np.array([[1,2 ], [3, 4], [5,6]]).shape

In [6]:
# Matriz de rotação para girar pontos em 90 graus no sentido anti-horário (0, -1), (1, 0)
matriz_rotacao = np.array([[0, -1], [1, 0]])
matriz_rotacao

array([[ 0, -1],
       [ 1,  0]])

## Tensores

In [ ]:
pip install tensorflow-cpu

In [3]:
import tensorflow as tf

In [6]:
# Criando um tensor tridimensional
tensor = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]], [[13, 14], [15, 16]]])
tensor.numpy().reshape(16, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16]], dtype=int32)